package Model;
// Generated Feb 6, 2020 6:59:27 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Depart generated by hbm2java
 */
@Entity
@Table(name = "depart", schema = "dbo", catalog = "Lab6")
public class Depart implements java.io.Serializable {

	private String id;
	private String name;
	private Set<Staffs> staffses = new HashSet<Staffs>(0);

	public Depart() {
	}

	public Depart(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public Depart(String id, String name, Set<Staffs> staffses) {
		this.id = id;
		this.name = name;
		this.staffses = staffses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "depart", cascade = CascadeType.REMOVE)
	public Set<Staffs> getStaffses() {
		return this.staffses;
	}

	public void setStaffses(Set<Staffs> staffses) {
		this.staffses = staffses;
	}

}
